version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: nestshop-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestshop-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/nestshop?schema=public"
      JWT_SECRET: "supersecret"
      JWT_REFRESH_SECRET: "superrefreshsecret"
      NODE_ENV: "production"
    ports:
      - "4000:4000"
    command: ["/app/entrypoint.sh"]

volumes:
  pgdata: